name: Create Archive

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: bump
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "BrassburgFixes-${{ steps.bump.outputs.new_tag }}.zip"
          exclusions: "*.git*"
      - name: Upload to GitHub
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "BrassburgFixes-${{ steps.bump.outputs.new_tag }}.zip"
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.bump.outputs.new_tag }}
          name: ${{ steps.bump.outputs.new_tag }}
          body: ${{ steps.bump.outputs.changelog }}
          commit: ${{ github.sha }}
